version: "3.9"

volumes:
  postgre_data:
  media_volume:

services:
  web:
    image: yatube_image
    container_name: yatube_project
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./yatube:/project/
      - media_volume:/project/media
    depends_on:
      - db

  redis:
    image: redis:6.2-alpine
    container_name: yatube_redis
    restart: always

  db:
    image: postgres:13.4-alpine
    container_name: yatube_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgre_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.20.1-alpine
    container_name: yatube_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./yatube/static:/static
      - media_volume:/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
